### PR TITLE
Add support for topic aliases

### PR DESCRIPTION
**Pull request by nhr**
This feature enables writers to add an `asciibinder-aliases` attribute to the top matter of any topic. The value of this attribute is a comma-delimited list of paths that will _redirect_ readers to this topic when the website is built and published.

By example:

* Originally this topic was `animals/chordates/platypus`
* Then it was `animals/look_like_ducks/platypus`
* Currently it is `creatures/poisonous_marsupials/platypus`

The top matter of this topic may be:

```
[[ponderous-platypus]]
= The Ponderous Platypus
{product-author}
{product-version}
:asciibinder-aliases: animals/chordates/platypus,animals/look_like_ducks/platypus
:data-uri:
:icons:

[.lead]
Let me tell you a thing or two about platypuses...
```

In this case, at the same point where AsciiBinder generates the file `creatures/poisonous_marsupials/platypus.html`, it will also generate two other files:

* `animals/chordates/platypus.html`
* `animals/look_like_ducks/platypus.html`

However, these files are a very simple pointer back to the current topic file.

### Caveats
Like the honey badger, AsciiBinder doesn't express a great level of care here. So if you have a real topic and an alias that both occur at the same path, one of two things will happen:

1. The alias may overwrite the topic or
2. The topic may overwrite the alias

Also, AsciiBinder goes through a lot of hoops to make it easy to preview content on your local machine before you publish. However, this is not easy to do with topic aliases. As long as your alias paths reflect the topic group / topic or topic group / topic subgroup / topic form of paths from `_topic_map.yml`, you will be okay.

@adellape / @vikram-redhat / @Fryguy please review.

### CODE REVIEW

**Comment by bexelbie** [comment]
I am curious why a redirect database was not chosen instead.  It seems this could lead to lots of overhead to maintain a site which one does not write for.

**Comment by nhr** [comment]
This is a fair point. As an alternative to the implementation here, I could support an 'Aliases' field to topic items in `_topic_map.yml`. Functionally it would work the same but the aliases would be specified in the map rather than the individual topics. This would also enable us to more easily detect and warn on alias / topic collisions. @bexelbie let me know what you think of that approach before I modify the feature.

**Comment by bexelbie** [comment]
@nhr I like this approach.  Can I add a request for two extensions that may or may not be part of the initial PR:

1. The ability to specify aliases that can redirect to offsite urls for situations where pages have moved out of the repo.  This is particularly critical when dealing with search rank/reputation.

2. The ability to specify aliases for things that should never be allowed to exist.  I want to think this through some, but in general, it would give you a way to mask off paths that are provided or blocked for non-AB build reasons.

**Comment by nhr** [comment]
@bexelbie - #1 is pretty easy. We could say that any alias string starting with *//: is used verbatim, and any alias _not_ starting that way will get "/<branch_dir>" appended to it so that it works as an internal-to-the-distro-branch redirect. #2 I think we need to talk through some more. I will push an update to this feature based on the topic_map approach plus your suggestion #1.

**Comment by nhr** [comment]
Actually, I just realized something. Your ideas both flip the logic. Right now, the topic map contains topic items that are _actually present_, and my suggestion is "Add `Alias` entries to topic in the topic map and I will create pointers at those alias paths which direct users back to this topic". However, your idea is of the form "Create topic entries that represent nonexistent paths and that provide a pointer to an actual path, which may or may not be in this docs set".

The risk of your approach is that if a "placeholder" entry redirects to a topic path that doesn't actually exist, then you are redirecting the reader into a 404, whereas my approach implicitly ensures that a topic exists to be redirected to. But in your approach, AsciiBinder could be instrumented to raise an error when an internal redirect doesn't actually map to anything.

What I like about your idea is that when someone "moves" a topic, they leave an entry in the topic map at the topic's original location with a pointer to the new location. On the flip side, in a sufficiently complex topic map, having a whole topic item entry for each alias makes the whole map harder to read (as opposed to a topic that has an 'Alias' field and a comma-delimited list of values).

**Comment by nhr** [comment]
@bexelbie - I've pushed a new commit that flips the logic and uses the topic map to do it. Considerably more code but:

* There's error checking with this approach
    * collision with real topics is not possible
    * "null pointers" to nonexistent topics are detected and cause failures
* Aliases have entries in the topic map, and are therefore managed the same way real topics are
* Aliases can point either to:
    * other topics in the same repo using shorthand
    * any `http(s)://`-based URL

Have a look and let me know what you think.

**Comment by bexelbie** [comment]
@nhr I looked at it briefly. I like the idea.  In my mind's eye, one could still have an alias appear in the menu.  If we are talking about 301 style dead links, then I understand not listing them.  However, I could also see value in listing them in some cases.

I am not sure what the motivating use case is here to know if this extension is warranted yet.

**Comment by nhr** [comment]
@bexelbie on the use of aliases in the nav tree - I thought about that. I am hesitant because the user experience would be: "hey, I clicked on foo => bar ended up on baz => other - is the nav tree broken?"

On the motivating use case: I currently hand-code every redirect that the OpenShift writers need, directly into the nginx server config. That's a problem for two reasons:

1. I am a bottleneck in their workflows and
2. When we move to a v3-based pipeline, hand-editing the nginx config will be a major problem

This is a high priority for us as the OpenShift docs are still hosted on v2, and we've already begun turning off the lights for Online v2.

**Comment by bexelbie** [comment]
@nhr I am in favour of merging this without aliases appearing in the tree and letting that get opened as a issue/PR when someone has a genuine use case/need.

**Pull request merged**
