### PR TITLE
Add dockerfile to run as a container

### PR DESCRIPTION
**Pull request by aweiteka**

### CODE REVIEW

**Comment by aweiteka** [comment]
@nhr please take a look. When merged I'll create an automated build in docker hub. This is a dependency for getting an automated docs workflow set up for docs.projectatomic.io

**Comment by nhr** [comment]
Unfortunately this is not complete. AsciiBinder supports [ditaa]-based diagramming, but in order to do so, AsciiBinder assumes that it is running in an environment that satisfies ditaa's Java requirement. See the [installation note on Java](http://www.asciibinder.org/latest/guides/user_guide.html#installing-asciibinder) for more on that.

**Comment by aweiteka** [comment]
@nhr good catch. Updated. This should work.

**Comment by nhr** [comment]
Almost there. You need to explicitly set the $JAVA_HOME variable so that it is available to AsciiBinder at runtime.

**Comment by aweiteka** [comment]
Updated, tested asciibinder. Not sure how to test the env var. Output:

```
bash-4.2# echo $JAVA_HOME
/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.95-2.6.4.0.el7_2.x86_64/jre/
bash-4.2# ls -l $JAVA_HOME
total 4
drwxr-xr-x.  2 root root  161 Mar 16 21:02 bin
drwxr-xr-x. 10 root root 4096 Mar 16 21:02 lib
bash-4.2# ls -l $JAVA_HOME/bin
total 160
-rwxr-xr-x. 1 root root   333 Jan 21 15:45 java
-rwxr-xr-x. 1 root root  7368 Jan 21 15:47 keytool
-rwxr-xr-x. 1 root root  7440 Jan 21 15:47 orbd
-rwxr-xr-x. 1 root root  7376 Jan 21 15:47 pack200
-rwxr-xr-x. 1 root root  7368 Jan 21 15:47 policytool
-rwxr-xr-x. 1 root root  7360 Jan 21 15:47 rmid
-rwxr-xr-x. 1 root root  7368 Jan 21 15:47 rmiregistry
-rwxr-xr-x. 1 root root  7376 Jan 21 15:47 servertool
-rwxr-xr-x. 1 root root  7448 Jan 21 15:47 tnameserv
-rwxr-xr-x. 1 root root 90744 Jan 21 15:47 unpack200
```

**Comment by nhr** [comment]
Looks good. Thanks for the PR!

**Pull request merged**
