### PR TITLE
Refactor "WARNING: ..." functionality

### PR DESCRIPTION
**Pull request by tnguyen-rh**

### CODE REVIEW

**Comment by tnguyen-rh** [comment]
@nhr @Fryguy WDYT?

**Comment by Fryguy** [comment]
The newline part feels like it should be the callers concern, and by that I mean the caller can just tack on a "\n" to the message if they want it.  I don't feel like that warrants adding a whole parameter.  but other wise, looks good!

**Comment by tnguyen-rh** [comment]
@Fryguy
I dislike the complexity, as well.  Unfortunately, i could not find a simpler way to maintain parity w/ pre-patch behavior ([here](https://github.com/redhataccess/ascii_binder/pull/43/files#diff-8aee177e98875aa404628c3bfcad6ea4L218), for example), where the caller outputs the newline at the **beginning** of the message (prior to outputting the `HEY: MESSAGE` line).

**Comment by Fryguy** [comment]
Oh i see you're *pre*pending it.  I didn't see that at first glance.

**Comment by Fryguy** [comment]
Thanks @tnguyen-rh !

**Pull request merged**
