### PR TITLE
GH#185: bump Ruby version and use necessary 'git config' command during build

### PR DESCRIPTION
**Pull request by peterroth**

### CODE REVIEW

**Comment by peterroth** [comment]
I built and ran the image successfully against openshift-docs, worked without issues.

**Comment by elmiko** [comment]
cc @vikram-redhat @gabriel-rh

**Comment by vikram-redhat** [comment]
@wgordon17

**Comment by peterroth** [comment]
Hello @wgordon17,
Could you please check if this pull request is correct?

**Comment by wgordon17** [comment]
So sorry on the delay, thank you for your contribution @peterroth 🎉

**Review by wgordon17 — APPROVED** [review]

**Comment by peterroth** [comment]
Sure, no worries.
Happy to help.

**Pull request merged**
