### PR TITLE
Object-ify Topic-related structures

### PR DESCRIPTION
**Pull request by nhr**
This is the second and likely largest refactor involved in making AsciiBinder a more OO program. The most significant change introduced here is foundational support for arbitrary depth in the topic map. Fully exposing this will impact page templates, however, so I am preserving the limitation until we are ready to push a new major release.

### CODE REVIEW

**Comment by nhr** [comment]
Hey @r0ckarong / @bexelbie / @Fryguy - if any of you can have a look at this PR, I'd appreciate it. It is pretty extensive but represents the lion's share of the OO-ification work. After this I have one more pass planned to tidy up the way that AsciiBinder interacts with the git repo and then I can move on to some sought-after new features.

**Comment by nhr** [comment]
Forgot to add @indigo423 to my plea for another code review...

**Comment by indigo423** [comment]
@nhr gave it a shot and works for me 👍

**Comment by nhr** [comment]
@indigo423 much obliged, sir! Thank you for giving it a go.

**Pull request merged**
